"""
Curated subset of legitimate Philippine educational institutions.
Levels: 'Basic' (elementary/junior-senior high) | 'Tertiary' (college/masteral)
Sourced from CHED-recognized institutions and DepEd public school divisions.
Prototype-grade: covers major/well-known schools; expandable.
"""

PH_SCHOOLS = [
    # --- NCR: State universities & colleges ---
    ("University of the Philippines Diliman", "Tertiary", "Quezon City", "NCR"),
    ("University of the Philippines Manila", "Tertiary", "Manila", "NCR"),
    ("University of the Philippines Los Banos", "Tertiary", "Los Banos", "CALABARZON"),
    ("Polytechnic University of the Philippines", "Tertiary", "Manila", "NCR"),
    ("Philippine Normal University", "Tertiary", "Manila", "NCR"),
    ("Technological University of the Philippines", "Tertiary", "Manila", "NCR"),
    ("Rizal Technological University", "Tertiary", "Mandaluyong", "NCR"),
    ("University of Makati", "Tertiary", "Makati", "NCR"),
    ("University of the City of Manila (PLM)", "Tertiary", "Manila", "NCR"),
    ("Quezon City University", "Tertiary", "Quezon City", "NCR"),
    ("University of Caloocan City", "Tertiary", "Caloocan", "NCR"),
    ("Navotas Polytechnic College", "Tertiary", "Navotas", "NCR"),
    ("Eulogio Amang Rodriguez Institute of Science and Technology", "Tertiary", "Manila", "NCR"),
    ("Marikina Polytechnic College", "Tertiary", "Marikina", "NCR"),
    ("Valenzuela City Polytechnic College", "Tertiary", "Valenzuela", "NCR"),
    # --- NCR: Private universities ---
    ("Ateneo de Manila University", "Tertiary", "Quezon City", "NCR"),
    ("De La Salle University", "Tertiary", "Manila", "NCR"),
    ("University of Santo Tomas", "Tertiary", "Manila", "NCR"),
    ("Far Eastern University", "Tertiary", "Manila", "NCR"),
    ("University of the East", "Tertiary", "Manila", "NCR"),
    ("Adamson University", "Tertiary", "Manila", "NCR"),
    ("Mapua University", "Tertiary", "Manila", "NCR"),
    ("National University", "Tertiary", "Manila", "NCR"),
    ("San Beda University", "Tertiary", "Manila", "NCR"),
    ("Centro Escolar University", "Tertiary", "Manila", "NCR"),
    ("Arellano University", "Tertiary", "Manila", "NCR"),
    ("Manuel L. Quezon University", "Tertiary", "Quezon City", "NCR"),
    ("New Era University", "Tertiary", "Quezon City", "NCR"),
    ("Miriam College", "Tertiary", "Quezon City", "NCR"),
    ("St. Paul University Manila", "Tertiary", "Manila", "NCR"),
    ("Our Lady of Fatima University", "Tertiary", "Valenzuela", "NCR"),
    ("University of Asia and the Pacific", "Tertiary", "Pasig", "NCR"),
    ("De La Salle-College of Saint Benilde", "Tertiary", "Manila", "NCR"),
    ("Asia Pacific College", "Tertiary", "Makati", "NCR"),
    ("STI Colleges (Global City)", "Tertiary", "Taguig", "NCR"),
    ("AMA Computer University", "Tertiary", "Quezon City", "NCR"),
    ("Lyceum of the Philippines University", "Tertiary", "Manila", "NCR"),
    ("Emilio Aguinaldo College", "Tertiary", "Manila", "NCR"),
    ("Philippine Christian University", "Tertiary", "Manila", "NCR"),
    ("University of Perpetual Help System DALTA", "Tertiary", "Las Pinas", "NCR"),
    # --- Luzon ---
    ("University of the Philippines Baguio", "Tertiary", "Baguio", "CAR"),
    ("Saint Louis University", "Tertiary", "Baguio", "CAR"),
    ("University of the Cordilleras", "Tertiary", "Baguio", "CAR"),
    ("Baguio Central University", "Tertiary", "Baguio", "CAR"),
    ("Benguet State University", "Tertiary", "La Trinidad", "CAR"),
    ("Mariano Marcos State University", "Tertiary", "Batac", "Ilocos"),
    ("University of Northern Philippines", "Tertiary", "Vigan", "Ilocos"),
    ("Northwestern University", "Tertiary", "Laoag", "Ilocos"),
    ("Don Mariano Marcos Memorial State University", "Tertiary", "San Fernando", "Ilocos"),
    ("Cagayan State University", "Tertiary", "Tuguegarao", "Cagayan Valley"),
    ("University of La Salette", "Tertiary", "Santiago", "Cagayan Valley"),
    ("Isabela State University", "Tertiary", "Echague", "Cagayan Valley"),
    ("Nueva Vizcaya State University", "Tertiary", "Bayombong", "Cagayan Valley"),
    ("Central Luzon State University", "Tertiary", "Science City of Munoz", "Central Luzon"),
    ("Bulacan State University", "Tertiary", "Malolos", "Central Luzon"),
    ("Tarlac State University", "Tertiary", "Tarlac City", "Central Luzon"),
    ("Bataan Peninsula State University", "Tertiary", "Balanga", "Central Luzon"),
    ("Pampanga State Agricultural University", "Tertiary", "Magalang", "Central Luzon"),
    ("Angeles University Foundation", "Tertiary", "Angeles City", "Central Luzon"),
    ("Holy Angel University", "Tertiary", "Angeles City", "Central Luzon"),
    ("University of the Assumption", "Tertiary", "San Fernando", "Central Luzon"),
    ("Don Honorio Ventura State University", "Tertiary", "Bacolor", "Central Luzon"),
    ("Aurora State College of Technology", "Tertiary", "Baler", "Central Luzon"),
    ("Nueva Ecija University of Science and Technology", "Tertiary", "Cabanatuan", "Central Luzon"),
    ("Wesleyan University Philippines", "Tertiary", "Cabanatuan", "Central Luzon"),
    ("Batangas State University", "Tertiary", "Batangas City", "CALABARZON"),
    ("Cavite State University", "Tertiary", "Indang", "CALABARZON"),
    ("Laguna State Polytechnic University", "Tertiary", "Santa Cruz", "CALABARZON"),
    ("University of Rizal System", "Tertiary", "Antipolo", "CALABARZON"),
    ("De La Salle University-Dasmariñas", "Tertiary", "Dasmariñas", "CALABARZON"),
    ("University of Perpetual Help System JONELTA", "Tertiary", "Biñan", "CALABARZON"),
    ("Lyceum of the Philippines University-Laguna", "Tertiary", "Calamba", "CALABARZON"),
    ("Mapua Malayan Colleges Laguna", "Tertiary", "Cabuyao", "CALABARZON"),
    ("San Sebastian College-Recoletos Cavite", "Tertiary", "Cavite City", "CALABARZON"),
    ("Colegio de San Juan de Letran", "Tertiary", "Manila", "NCR"),
    ("Manuel S. Enverga University Foundation", "Tertiary", "Lucena", "CALABARZON"),
    ("Southern Luzon State University", "Tertiary", "Lucban", "CALABARZON"),
    ("University of Batangas", "Tertiary", "Batangas City", "CALABARZON"),
    ("Camarines Sur Polytechnic Colleges", "Tertiary", "Naga", "Bicol"),
    ("Bicol University", "Tertiary", "Legazpi", "Bicol"),
    ("Ateneo de Naga University", "Tertiary", "Naga", "Bicol"),
    ("University of Nueva Caceres", "Tertiary", "Naga", "Bicol"),
    ("Partido State University", "Tertiary", "Goa", "Bicol"),
    ("Catanduanes State University", "Tertiary", "Virac", "Bicol"),
    ("Dr. Emilio B. Espinosa Sr. Memorial State College of Agriculture and Technology", "Tertiary", "Mandaon", "Bicol"),
    ("Palawan State University", "Tertiary", "Puerto Princesa", "MIMAROPA"),
    ("Mindoro State University", "Tertiary", "Calapan", "MIMAROPA"),
    ("Marinduque State University", "Tertiary", "Boac", "MIMAROPA"),
    ("Romblon State University", "Tertiary", "Odiongan", "MIMAROPA"),
    ("Western Philippines University", "Tertiary", "Aborlan", "MIMAROPA"),
    # --- Visayas ---
    ("University of San Carlos", "Tertiary", "Cebu City", "Central Visayas"),
    ("University of San Jose-Recoletos", "Tertiary", "Cebu City", "Central Visayas"),
    ("University of the Visayas", "Tertiary", "Cebu City", "Central Visayas"),
    ("Cebu Institute of Technology University", "Tertiary", "Cebu City", "Central Visayas"),
    ("Southwestern University", "Tertiary", "Cebu City", "Central Visayas"),
    ("Cebu Normal University", "Tertiary", "Cebu City", "Central Visayas"),
    ("Bohol Island State University", "Tertiary", "Tagbilaran", "Central Visayas"),
    ("Silliman University", "Tertiary", "Dumaguete", "Central Visayas"),
    ("Foundation University", "Tertiary", "Dumaguete", "Central Visayas"),
    ("Negros Oriental State University", "Tertiary", "Dumaguete", "Central Visayas"),
    ("University of Negros Occidental-Recoletos", "Tertiary", "Bacolod", "Western Visayas"),
    ("University of St. La Salle", "Tertiary", "Bacolod", "Western Visayas"),
    ("West Visayas State University", "Tertiary", "Iloilo City", "Western Visayas"),
    ("University of the Philippines Visayas", "Tertiary", "Miagao", "Western Visayas"),
    ("Central Philippine University", "Tertiary", "Iloilo City", "Western Visayas"),
    ("Aklan State University", "Tertiary", "Banga", "Western Visayas"),
    ("Capiz State University", "Tertiary", "Roxas City", "Western Visayas"),
    ("Guimaras State University", "Tertiary", "Buenavista", "Western Visayas"),
    ("Eastern Visayas State University", "Tertiary", "Tacloban", "Eastern Visayas"),
    ("Leyte Normal University", "Tertiary", "Tacloban", "Eastern Visayas"),
    ("University of the Philippines Tacloban", "Tertiary", "Tacloban", "Eastern Visayas"),
    ("Visayas State University", "Tertiary", "Baybay", "Eastern Visayas"),
    ("Palompon Institute of Technology", "Tertiary", "Palompon", "Eastern Visayas"),
    ("Samar State University", "Tertiary", "Catbalogan", "Eastern Visayas"),
    ("Biliran Province State University", "Tertiary", "Naval", "Eastern Visayas"),
    # --- Mindanao ---
    ("University of the Philippines Mindanao", "Tertiary", "Davao City", "Davao"),
    ("University of the Philippines Davao", "Tertiary", "Davao City", "Davao"),
    ("Ateneo de Davao University", "Tertiary", "Davao City", "Davao"),
    ("University of Mindanao", "Tertiary", "Davao City", "Davao"),
    ("University of Southeastern Philippines", "Tertiary", "Davao City", "Davao"),
    ("Davao del Sur State College", "Tertiary", "Digos", "Davao"),
    ("Davao Oriental State University", "Tertiary", "Mati", "Davao"),
    ("Davao de Oro State College", "Tertiary", "Compostela", "Davao"),
    ("Mindanao State University - Main", "Tertiary", "Marawi", "BARMM"),
    ("Mindanao State University - Iligan Institute of Technology", "Tertiary", "Iligan", "Northern Mindanao"),
    ("University of Science and Technology of Southern Philippines", "Tertiary", "Cagayan de Oro", "Northern Mindanao"),
    ("Xavier University - Ateneo de Cagayan", "Tertiary", "Cagayan de Oro", "Northern Mindanao"),
    ("Liceo de Cagayan University", "Tertiary", "Cagayan de Oro", "Northern Mindanao"),
    ("Central Mindanao University", "Tertiary", "Maramag", "Northern Mindanao"),
    ("Mindanao State University - Bukidnon", "Tertiary", "Malaybalay", "Northern Mindanao"),
    ("Bukidnon State University", "Tertiary", "Malaybalay", "Northern Mindanao"),
    ("Misamis University", "Tertiary", "Ozamiz", "Northern Mindanao"),
    ("University of the Immaculate Conception", "Tertiary", "Davao City", "Davao"),
    ("Ateneo de Zamboanga University", "Tertiary", "Zamboanga City", "Zamboanga"),
    ("Western Mindanao State University", "Tertiary", "Zamboanga City", "Zamboanga"),
    ("Jose Rizal Memorial State University", "Tertiary", "Dapitan", "Zamboanga"),
    ("University of San Agustin", "Tertiary", "Iloilo City", "Western Visayas"),
    ("Notre Dame of Dadiangas University", "Tertiary", "General Santos", "SOCCSKSARGEN"),
    ("University of Southern Mindanao", "Tertiary", "Kabacan", "SOCCSKSARGEN"),
    ("Cotabato State University", "Tertiary", "Cotabato City", "BARMM"),
    ("Sultan Kudarat State University", "Tertiary", "Tacurong", "SOCCSKSARGEN"),
    ("Mindanao State University - General Santos", "Tertiary", "General Santos", "SOCCSKSARGEN"),
    ("University of the Philippines - School of Health Sciences", "Tertiary", "Palo", "Eastern Visayas"),
    ("Caraga State University", "Tertiary", "Butuan", "Caraga"),
    ("Surigao State College of Technology", "Tertiary", "Surigao City", "Caraga"),
    ("Father Saturnino Urios University", "Tertiary", "Butuan", "Caraga"),
    ("University of the East Ramon Magsaysay Memorial Medical Center", "Tertiary", "Quezon City", "NCR"),
    # --- Notable basic-education institutions (representative, national coverage) ---
    ("Philippine Science High School - Main Campus", "Basic", "Quezon City", "NCR"),
    ("Philippine Science High School - Southern Mindanao Campus", "Basic", "Davao City", "Davao"),
    ("Quezon City Science High School", "Basic", "Quezon City", "NCR"),
    ("Manila Science High School", "Basic", "Manila", "NCR"),
    ("Makati Science High School", "Basic", "Makati", "NCR"),
    ("University of Santo Tomas High School", "Basic", "Manila", "NCR"),
    ("Ateneo de Manila High School", "Basic", "Quezon City", "NCR"),
    ("De La Salle Santiago Zobel School", "Basic", "Muntinlupa", "NCR"),
    ("San Beda College Alabang (High School)", "Basic", "Muntinlupa", "NCR"),
    ("Xavier School", "Basic", "San Juan", "NCR"),
    ("La Salle Green Hills", "Basic", "Mandaluyong", "NCR"),
    ("Colegio San Agustin Makati", "Basic", "Makati", "NCR"),
    ("Pamantasan ng Lungsod ng Maynila High School", "Basic", "Manila", "NCR"),
    ("Ramon Magsaysay High School", "Basic", "Manila", "NCR"),
    ("Quezon High School", "Basic", "Quezon City", "NCR"),
    ("Science High School (Baguio City National High School)", "Basic", "Baguio", "CAR"),
    ("University of the Philippines Rural High School", "Basic", "Los Banos", "CALABARZON"),
    ("Marikina High School", "Basic", "Marikina", "NCR"),
    ("Pasig City Science High School", "Basic", "Pasig", "NCR"),
    ("Taguig Science High School", "Basic", "Taguig", "NCR"),
    ("Balanga National High School", "Basic", "Balanga", "Central Luzon"),
    ("Tarlac National High School", "Basic", "Tarlac City", "Central Luzon"),
    ("Baguio City National High School", "Basic", "Baguio", "CAR"),
    ("Cebu City National Science High School", "Basic", "Cebu City", "Central Visayas"),
    ("Ramon Teves Pastor Memorial Dumaguete Science High School", "Basic", "Dumaguete", "Central Visayas"),
    ("Iloilo National High School", "Basic", "Iloilo City", "Western Visayas"),
    ("Davao City National High School", "Basic", "Davao City", "Davao"),
    ("Zamboanga City National High School", "Basic", "Zamboanga City", "Zamboanga"),
    ("Butuan City National High School", "Basic", "Butuan", "Caraga"),
    ("Leyte National High School", "Basic", "Tacloban", "Eastern Visayas"),
    ("Cagayan National High School", "Basic", "Tuguegarao", "Cagayan Valley"),
    ("San Fernando National High School", "Basic", "San Fernando", "Ilocos"),
    ("Naga National High School", "Basic", "Naga", "Bicol"),
    ("Puerto Princesa City National Science High School", "Basic", "Puerto Princesa", "MIMAROPA"),
    ("Mindanao State University - Integrated Laboratory School", "Basic", "Marawi", "BARMM"),
    ("General Santos City National High School", "Basic", "General Santos", "SOCCSKSARGEN"),
]
